# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java Development Kit 13
      uses: actions/setup-java@v1
      with:
        java-version: 13.0.0
    - name: Build with Maven
      run: xvfb-run --server-args="-screen 0, 800x600x8" mvn verify -B package --file pom.xml
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: Report Jacoco
        path: target/site/jacoco
